<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Notre Site E-Commerce</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
   <link rel="stylesheet" href="assets/styles/css/index.css">
</head>

<body>
      <header>
            <?php 
            if(isset($_SESSION["user_id"]))
            {
               require 'views/user/connected/_header.phtml';
            }
            else{
               require 'views/user/guest/_header.phtml';
            }
            ?>
      </header>
      
   <main>
      <?php require $this->template; ?>
   </main>
   
   <script src="assets/js/main.js"></script>
</body>

</html>