
<head>
    <title>Mon compte utilisateur</title>
</head>

<h1>Mon compte</h1>

    <h2>Formulaire d'adresse</h2>
    <form action="index.php?route=add-adresse" method="POST">

        <label for="prenom">Username :</label>
        <input type="text" id="prenom" name="prenom" required><br><br>

        <label for="adresse">Adresse :</label>
        <input type="text" id="adresse" name="adresse" required><br><br>

        <label for="ville">Ville :</label>
        <input type="text" id="ville" name="ville" required><br><br>

        <label for="codepostal">Code postal :</label>
        <input type="text" id="codepostal" name="codepostal" required><br><br>

        <label for="pays">Pays :</label>
        <input type="text" id="pays" name="pays" required><br><br>

        <input type="submit" value="Soumettre">
    </form>
    
    <h2>Réinitialisation du mot de passe</h2>
    <form action="index.php?route=remote-mdp" method="POST">
        <label for="email">Adresse e-mail :</label>
        <input type="email" id="email" name="email" required><br><br>

        <label for="nouveauMotDePasse">Nouveau mot de passe :</label>
        <input type="password" id="nouveauMotDePasse" name="nouveauMotDePasse" required><br><br>

        <label for="confirmationMotDePasse">Confirmer le nouveau mot de passe :</label>
        <input type="password" id="confirmationMotDePasse" name="confirmationMotDePasse" required><br><br>

        <input type="submit" value="Réinitialiser le mot de passe">
    </form>
    
    <!-- order creation form -->
   <form action="index.php?route=order-create" method="POST" aria-label="" id="order-create">
      <section aria-labelledby="title-cart">
         <h3 id="title-cart">Panier</h3>
         <ul id="cart">

         </ul>
      </section>
      <div>
         <h3>Adresse de livraison</h3>
         <div class="d-flex gap-2">
            <label for="address_code_postal" class="visually-hidden">Code postal</label>
            <input class="form-control" type="number" name="address_code_postal" value="" placeholder="Code postal" id="address_code_postal">
            <label for="address_pays" class="visually-hidden">Pays</label>
            <input class="form-control" type="text" name="address_pays" value="" placeholder="France" id="address_pays">
         </div>
         <label for="address_details"></label>
         <textarea class="form-control" type="text" 
                  name="address_details" value="" 
                  placeholder="Ex: 1 rue Dufour" id="address_details">
         </textarea>
      </div>
      <button class="btn btn-primary" type="submit">Valider la commande</button>
   </form>
