
<head>
    <title>Mon compte utilisateur</title>
</head>

<h1>Mon compte</h1>

    <h2>Formulaire d'adresse</h2>
    <span class="advert"><?php
    if(isset($this->data["message"]))
    {
        echo $this->data["message"];
    }
    ?></span>
    <form action="index.php?route=add-address" method="POST">

        <label for="adresse">Adresse :</label>
        <input type="text" id="adresse" name="adresse" required><br><br>

        <label for="ville">Ville :</label>
        <input type="text" id="ville" name="ville" required><br><br>

        <label for="codepostal">Code postal :</label>
        <input type="text" id="codepostal" name="codepostal" required><br><br>

        <label for="pays">Pays :</label>
        <input type="text" id="pays" name="pays" required><br><br>

        <input type="submit" value="Soumettre">
    </form>
    
    <h2>Réinitialisation du mot de passe</h2>
    <form action="index?route=reset-mdp" method="POST">
        <label for="email">Adresse e-mail :</label>
        <input type="email" id="email" name="email" required><br><br>

        <label for="nouveauMotDePasse">Nouveau mot de passe :</label>
        <input type="password" id="nouveauMotDePasse" name="nouveauMotDePasse" required><br><br>

        <label for="confirmationMotDePasse">Confirmer le nouveau mot de passe :</label>
        <input type="password" id="confirmationMotDePasse" name="confirmationMotDePasse" required><br><br>

        <input type="submit" value="Réinitialiser le mot de passe">
    </form>

    <section>
        <table>
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Quantité</th>
                    <th>Prix/U</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                <?php
                
                
                ?>
            </tbody>
        </table>
    </section>