<h1>Créer un compte</h1>
<form action="index.php?route=user-register" method="POST">

    <label for="username">Username</label>
    <input type="text" id="username" name="username" required>
    
    <label for="first_name">Username</label>
    <input type="text" id="first_name" name="first_name" required>
    
    <label for="last_name">Username</label>
    <input type="text" id="last_name" name="last_name" required>
    
    <label for="email">Email</label>
    <input type="email" id="email" name="email" required>

    <label for="password">Mot de passe</label>
    <input type="password" id="password" name="password" required>
   
    <label for="confirm-password">Confirmer votre Mot de passe</label>
    <input type="password" id="confirm-password" name="confirm-password" required>

    <input type="submit" value="Créer votre compte" class="noJS">
</form>